package com.totp.totp.controller;

/**
 * @author machao
 * @date 2019/7/22
 * @time 11:15
 * @description
 **/
public class Demo {

    public static void main(String[] args) {
        String bfSql = "SELECT  sum(s2c_byte_num) * 8 / 300 AS num, 'traffic_in' AS type FROM bandwidth_log  WHERE __time >= TIME_SHIFT(TIME_FLOOR (CURRENT_TIMESTAMP, 'PT5M'),'PT10M' ,-1) AND __time < TIME_SHIFT(TIME_FLOOR (CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1)  UNION ALL SELECT sum(c2s_byte_num) * 8 / 300 AS num,'traffic_out' AS type from bandwidth_log WHERE __time >= TIME_SHIFT(TIME_FLOOR (CURRENT_TIMESTAMP, 'PT5M'),'PT10M' ,-1)AND __time < TIME_SHIFT(TIME_FLOOR (CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1)  UNION ALL  SELECT COALESCE (sum(close_conn_num), 0) / 300 AS num,'close_conn_num' AS type FROM traffic_metrics_log WHERE __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT10M' ,-1) AND __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1)  UNION ALL SELECT COALESCE(sum(live_conn_num), 0) / 300 AS num,'live_conn_num' AS type FROM traffic_metrics_log WHERE __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT10M' ,-1)AND __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1)  UNION ALL SELECT COALESCE(sum(new_conn_num), 0) / 300 AS num,'new_conn_num' AS type FROM traffic_metrics_log WHERE __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT10M' ,-1) AND __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1)  UNION ALL SELECT COALESCE(sum(hits), 0) / 300 AS num,'drop_num' AS type FROM policy_hits_log WHERE __time = TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1) AND action = 16 UNION ALL SELECT COALESCE(sum(hits), 0) / 300 AS num,'manipulate_num' AS type FROM policy_hits_log WHERE __time = TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1) AND action = 48 UNION ALL SELECT COALESCE(sum(hits), 0) / 300 AS num,'bypass_num' AS type FROM session_intercept_hits_log WHERE __time = TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP, 'PT5M'),'PT5M' ,-1) AND action = 128 union all select  COALESCE(sum(hits),0) /300 as num,'dynamic_bypass_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and intercept_state=0  union all select  COALESCE(sum(hits),0) /300 as num,'no_pinning_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and pinningst=0  union all select  COALESCE(sum(hits),0) /300 as num,'maybe_pinning_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and pinningst=2  union all select  COALESCE(sum(hits),0) /300 as num,'yes_pinning_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and pinningst=1";
        String yhSql = "select  sum(s2c_byte_num)*8/300 as num, 'traffic_in' as type from bandwidth_log where  __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT10M',-1) and __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1)   union all select  sum(c2s_byte_num)*8/300 as num, 'traffic_out' as type from bandwidth_log where  __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT10M',-1) and __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1)  union all select COALESCE(sum(close_conn_num),0)/300 as num,'close_conn_num' as type  from traffic_metrics_log where   __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT10M',-1) and __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) union all select  COALESCE(sum(live_conn_num),0) /300 as num,'live_conn_num' as type from traffic_metrics_log  where   __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT10M',-1) and __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) union all select    COALESCE(sum(new_conn_num),0) /300 as num,'new_conn_num' as type from traffic_metrics_log  where   __time >= TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT10M',-1) and __time < TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) union all select    COALESCE(sum(hits),0) /300 as num,'drop_num' as type from policy_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and action=16 union all select    COALESCE(sum(hits),0) /300 as num,'manipulate_num' as type from policy_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and action=48 union all select    COALESCE(sum(hits),0) /300 as num,'bypass_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and action=128 union all select  COALESCE(sum(hits),0) /300 as num,'dynamic_bypass_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and intercept_state=0 union all select  COALESCE(sum(hits),0) /300 as num,'no_pinning_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and pinningst=0 union all select  COALESCE(sum(hits),0) /300 as num,'maybe_pinning_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and pinningst=2 union all select  COALESCE(sum(hits),0) /300 as num,'yes_pinning_num' as type from session_intercept_hits_log where  __time=TIME_SHIFT(TIME_FLOOR(CURRENT_TIMESTAMP,'PT5M'),'PT5M',-1) and pinningst=1";
        bfSql = bfSql.replace(" ","").toUpperCase();
        yhSql = yhSql.replace(" ","").toUpperCase();
        System.out.println(bfSql.length());
        System.out.println(yhSql.length());
        System.out.println(bfSql.equals(yhSql));
    }

}
